// build-types.mjs: regenerate ltx-sdk.d.ts from the JSDoc in ltx-sdk.js.
//
// Usage: node build-types.mjs [outDir]   (default: this directory)
// Requires the TypeScript compiler (`tsc`) on PATH.
//
// tsc emits Node's `Buffer` wherever the JSDoc says Buffer. Consumers without
// @types/node cannot resolve that name, so the byte-array parameters and
// results are rewritten to `Uint8Array` (Node's Buffer is a Uint8Array
// subclass, so Buffers are still accepted).
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = process.argv[2] || here;
const tmp = mkdtempSync(join(tmpdir(), 'ltx-dts-'));

try {
  execFileSync('tsc', [
    join(here, 'ltx-sdk.js'),
    '--allowJs', '--declaration', '--emitDeclarationOnly',
    '--target', 'es2020', '--outDir', tmp,
  ], { stdio: 'inherit' });

  const body = readFileSync(join(tmp, 'ltx-sdk.d.ts'), 'utf8')
    .split('\n')
    .map((line) => (/^\s*(\/\*\*|\*)/.test(line) ? line : line.replace(/\bBuffer\b/g, 'Uint8Array')))
    .join('\n')
    .replace(/Uint8Array \| Uint8Array/g, 'Uint8Array');

  const header =
    '// Type declarations for interplanet-ltx (ltx-sdk.js).\n' +
    '// GENERATED by `make types` (node build-types.mjs) from the JSDoc in ltx-sdk.js.\n' +
    '// Do not edit by hand: change the JSDoc and regenerate.\n';
  writeFileSync(join(outDir, 'ltx-sdk.d.ts'), header + body);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
