/**
 * build-esm.mjs — writes ltx-sdk.mjs, the ES module entry of the package.
 *
 * ltx-sdk.js is a UMD file. Node's `import` of a CommonJS file only finds the
 * named exports it can see statically, which for the UMD wrapper is none, so
 * `import { createPlan } from 'interplanet-ltx'` would fail. ltx-sdk.mjs
 * re-exports every property of the CommonJS module by name.
 *
 *   node build-esm.mjs          regenerate ltx-sdk.mjs
 *   node build-esm.mjs --check  exit 1 if ltx-sdk.mjs is stale
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, 'ltx-sdk.mjs');
const sdk = createRequire(import.meta.url)('./ltx-sdk.js');
const names = Object.keys(sdk).sort();

const text = [
  '// Generated by build-esm.mjs from ltx-sdk.js. Do not edit.',
  '// ES module entry: re-exports the CommonJS/UMD ltx-sdk.js by name.',
  "import sdk from './ltx-sdk.js';",
  '',
  'export default sdk;',
  'export const {',
  ...names.map((n) => `  ${n},`),
  '} = sdk;',
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (!existsSync(out) || readFileSync(out, 'utf8') !== text) {
    console.error("ltx-sdk.mjs is stale: run 'node build-esm.mjs'");
    process.exit(1);
  }
  console.log(`ltx-sdk.mjs current (${names.length} named exports)`);
} else {
  writeFileSync(out, text, 'utf8');
  console.log(`wrote ltx-sdk.mjs (${names.length} named exports)`);
}
