// Type declarations for interplanet-ltx (ltx-sdk.js).
// GENERATED by `make types` (node build-types.mjs) from the JSDoc in ltx-sdk.js.
// Do not edit by hand: change the JSDoc and regenerate.
export const VERSION: "1.1.0";
export const SEG_TYPES: string[];
export const DEFAULT_QUANTUM: 5;
export const DEFAULT_SEGMENTS: {
    type: string;
    q: number;
}[];
export const DELAY_VIOLATION_WARN_S: 120;
export const DELAY_VIOLATION_DEGRADE_S: 300;
export const LOCK_TIMEOUT_FACTOR: 2;
/**
 * Create a new LTX session plan.
 *
 * @param {object} opts
 * @param {string}   [opts.title]            Session title
 * @param {string}   [opts.start]            ISO 8601 UTC start time (default: 5 min from now)
 * @param {number}   [opts.quantum]          Minutes per quantum (default: DEFAULT_QUANTUM = 5)
 * @param {string}   [opts.mode]             Protocol mode (default: 'LTX')
 * @param {object[]} [opts.nodes]            Explicit node list (overrides hostName/remoteName)
 * @param {string}   [opts.hostName]         Host node name (default: 'Earth HQ')
 * @param {string}   [opts.hostLocation]     Host location key (default: 'earth')
 * @param {string}   [opts.remoteName]       Participant node name (default: 'Mars Hab-01')
 * @param {string}   [opts.remoteLocation]   Participant location key (default: 'mars')
 * @param {number}   [opts.delay]            One-way signal delay in seconds (default: 0)
 * @param {object[]} [opts.segments]         Segment template (default: DEFAULT_SEGMENTS)
 * @returns {object} LTX plan config (v2)
 */
export function createPlan(opts: {
    title?: string | undefined;
    start?: string | undefined;
    quantum?: number | undefined;
    mode?: string | undefined;
    nodes?: object[] | undefined;
    hostName?: string | undefined;
    hostLocation?: string | undefined;
    remoteName?: string | undefined;
    remoteLocation?: string | undefined;
    delay?: number | undefined;
    segments?: object[] | undefined;
}): object;
/**
 * Upgrade a v1 config (txName/rxName/delay) to v2 schema (nodes[]).
 * v2 configs are returned unchanged.
 * The optional relay field { endpoint, tls_fingerprint, delay_mode } is preserved.
 * @param {object} cfg
 * @param {string}  [cfg.relay.endpoint]        Relay server URL
 * @param {string}  [cfg.relay.tls_fingerprint] Pre-agreed shared secret for frame auth
 * @param {string}  [cfg.relay.delay_mode]      "oneway" or "roundtrip" (default: oneway)
 * @returns {object} v2 config
 */
export function upgradeConfig(cfg: object): object;
/**
 * Explicitly upgrade a plan to v3 (LTX-SPECIFICATION.md §4.4).
 * NEVER automatic: v3 fields must not be injected into a v2 plan, because the
 * frozen v2 planId hash is insertion-order-sensitive — the upgraded plan is a
 * NEW plan with a new (v3) planId. The input is not mutated.
 *
 * @param {object} cfg               LTX plan config (v1 or v2)
 * @param {object} [extras]          v3 fields to merge (e.g. { delays, planVersion })
 * @param {object} [extras.delays]   Pair delay matrix { 'A|B': seconds } (sorted-id keys)
 * @param {number} [extras.planVersion]  Plan version counter (default 1)
 * @returns {object} New v3 plan config
 * @throws {Error} err.code 'reserved_streams' | 'reserved_branching' (§3.5, §7)
 */
export function upgradePlanToV3(cfg: object, extras?: {
    delays?: object | undefined;
    planVersion?: number | undefined;
}): object;
/**
 * Validate a v2 or v3 plan against the wire format (spec/ltx-schema.json,
 * LTX-SPECIFICATION.md §4) and the reserved-field rules (§3.5 streams,
 * §7 branching). v1 configs must be upgraded (upgradeConfig) first.
 * Pure; never throws.
 *
 * Error codes: not_an_object, invalid_version, missing_field, invalid_field,
 * invalid_quantum, invalid_mode, invalid_nodes, invalid_host, duplicate_node_id,
 * invalid_segment, unknown_speaker, v3_field_in_v2, invalid_delays,
 * reserved_streams, reserved_branching.
 *
 * @param {object} plan
 * @returns {{ valid: boolean, errors: Array<{code:string, path:string, message:string}> }}
 */
export function validatePlan(plan: object): {
    valid: boolean;
    errors: Array<{
        code: string;
        path: string;
        message: string;
    }>;
};
/**
 * Compute the timed segment array for a plan config.
 *
 * @param {object} cfg  LTX plan config (v1 or v2)
 * @returns {Array<{type:string, q:number, start:Date, end:Date, durMin:number}>}
 */
export function computeSegments(cfg: object): Array<{
    type: string;
    q: number;
    start: Date;
    end: Date;
    durMin: number;
}>;
/**
 * Compute timed segments for a multi-party (N>2) plan.
 * SPEAK segments cycle round-robin through all nodes.
 * RELAY segments are assigned to the next speaker (receiver).
 * REST/BUFFER/PAD/other segments are assigned to the host node.
 * Falls back to computeSegments() for 2-node plans.
 *
 * @param {object} plan  LTX plan config (v1 or v2)
 * @returns {Array<{segType:string, nodeId:string, startMs:number, endMs:number, durationMs:number}>}
 */
export function computeSegmentsMulti(plan: object): Array<{
    segType: string;
    nodeId: string;
    startMs: number;
    endMs: number;
    durationMs: number;
}>;
/**
 * Build a flat delay matrix for all ordered node pairs in a plan.
 * Every entry is pairDelay(plan, from, to) (LTX-SPECIFICATION.md §3.7.3):
 * - a v3 pair matrix entry (plan.delays) is authoritative where present;
 * - HOST to node: that node's declared (HOST-relative) delay;
 * - node to node (neither is HOST): the SUM of both HOST-relative delays.
 *   This is the conservative upper bound via the HOST vertex (a signal
 *   relayed through HOST travels both legs), not the max of the two.
 * The matrix is symmetric: from/to and to/from carry the same delay.
 *
 * @param {object} plan  LTX plan config (v1, v2 or v3)
 * @returns {Array<{fromId:string, fromName:string, toId:string, toName:string, delaySeconds:number}>}
 */
export function buildDelayMatrix(plan: object): Array<{
    fromId: string;
    fromName: string;
    toId: string;
    toName: string;
    delaySeconds: number;
}>;
/**
 * One-way delay in seconds between two nodes (LTX-SPECIFICATION.md §3.7).
 * A v3 pair matrix (plan.delays, sorted-id 'A|B' keys) is authoritative where
 * present; otherwise the conservative fallback: HOST pairs use the node's
 * declared delay, non-HOST pairs the sum of both HOST-relative delays
 * (a safe upper bound via the HOST vertex).
 *
 * @param {object} cfg      LTX plan config (v1, v2 or v3)
 * @param {string} nodeIdA
 * @param {string} nodeIdB
 * @returns {number} one-way delay in seconds
 */
export function pairDelay(cfg: object, nodeIdA: string, nodeIdB: string): number;
/**
 * Compute the timed segment array from viewer V's perspective
 * (LTX-SPECIFICATION.md §14.3): a segment attributed to speaker S starts for
 * V at segStart + pairDelay(S, V). Unattributed segments keep their times.
 *
 * @param {object} cfg           LTX plan config (v1, v2 or v3)
 * @param {string} viewerNodeId  Node id of the viewing attendee
 * @returns {Array<{type:string, q:number, start:Date, end:Date, durMin:number,
 *   speaker?:string, label?:string, perspective:'transmit'|'receive'|'neutral',
 *   arrivalOffsetS:number}>}
 */
export function computeSegmentsFor(cfg: object, viewerNodeId: string): Array<{
    type: string;
    q: number;
    start: Date;
    end: Date;
    durMin: number;
    speaker?: string;
    label?: string;
    perspective: "transmit" | "receive" | "neutral";
    arrivalOffsetS: number;
}>;
/**
 * Total session duration in minutes.
 * @param {object} cfg
 * @returns {number}
 */
export function totalMin(cfg: object): number;
/**
 * Compute the deterministic plan ID string for a config.
 * Matches the ID generated by ltx.html and api/ltx.php.
 *
 * @param {object} cfg
 * @returns {string}  e.g. "LTX-20260101-EARTHHQ-MARSHA-v2-a3b2c1d0"
 */
export function makePlanId(cfg: object): string;
/**
 * Encode a plan config to a URL hash fragment (#l=…).
 * @param {object} cfg
 * @returns {string}
 */
export function encodeHash(cfg: object): string;
/**
 * Decode a plan config from a URL hash fragment.
 * Accepts "#l=…" or just "l=…" or the raw base64 token.
 * Returns null if the hash is invalid.
 *
 * @param {string} hash
 * @returns {object|null}
 */
export function decodeHash(hash: string): object | null;
/**
 * Build perspective URLs for all nodes in a plan.
 *
 * @param {object} cfg      LTX plan config
 * @param {string} baseUrl  Base page URL (e.g. "https://interplanet.live/ltx.html")
 * @returns {Array<{nodeId:string, name:string, role:string, url:string}>}
 */
export function buildNodeUrls(cfg: object, baseUrl: string): Array<{
    nodeId: string;
    name: string;
    role: string;
    url: string;
}>;
/**
 * Generate LTX-extended iCalendar (.ics) content for a plan.
 * Includes LTX-NODE, LTX-DELAY, LTX-LOCALTIME extension properties.
 * With options.viewerNodeId, emits the per-attendee form (§14.5): one VEVENT
 * per segment at that viewer's local arrival times.
 *
 * @param {object} cfg
 * @param {object} [options]
 * @param {string} [options.viewerNodeId]  Per-attendee export viewer node id
 * @returns {string}  ICS text
 */
export function generateICS(cfg: object, options?: {
    viewerNodeId?: string | undefined;
}): string;
/**
 * Build a conference segment template over the presenting nodes
 * (Story 71.2 · LTX-SPECIFICATION.md §14.2).
 * Presenting nodes = every node that is not an OBSERVER.
 * Rotation invariant ('rotate'): across N cycles, each node opens exactly once
 * — cycle c opens with presenting-node index c mod N (§14.4).
 *
 * @param {object[]} nodes                LTX node list
 * @param {object}   [options]
 * @param {number}   [options.cycles=1]   Number of full cycles (each node presents once per cycle)
 * @param {number}   [options.blockQ=3]   Quanta per presenting Block
 * @param {number}   [options.confirmQ=2] Quanta for the PLAN_CONFIRM opener
 * @param {number}   [options.mergeQ=2]   Quanta for the closing MERGE (0 to omit)
 * @param {number}   [options.bufferQ=1]  Quanta for the trailing BUFFER (0 to omit)
 * @param {number}   [options.caucusQ=0]  Insert a CAUCUS of this many quanta between cycles
 * @param {string}   [options.fairness='rotate']  'rotate' or 'fixed' (plan order)
 * @param {object}   [options.labels]     Optional label per node id, e.g. { N1: 'Mars Field Report' }
 * @returns {Array<{type:string, q:number, speaker?:string, label?:string}>}
 */
export function buildConferenceAgenda(nodes: object[], options?: {
    cycles?: number | undefined;
    blockQ?: number | undefined;
    confirmQ?: number | undefined;
    mergeQ?: number | undefined;
    bufferQ?: number | undefined;
    caucusQ?: number | undefined;
    fairness?: string | undefined;
    labels?: object | undefined;
}): Array<{
    type: string;
    q: number;
    speaker?: string;
    label?: string;
}>;
/**
 * Score per-node slot desirability over a plan's attributed segments (§14.4).
 * Desirability of attributed slot i (of k) = (k - i) / k, so the opening slot
 * scores 1 and the final slot 1/k. Organisers use the report to spot
 * imbalances when deviating from fair rotation.
 *
 * @param {object} cfg  LTX plan config (v1, v2 or v3)
 * @returns {Array<{nodeId:string, slots:number[], openings:number, score:number}>}
 *   sorted by score desc, then nodeId asc
 */
export function primeTimeReport(cfg: object): Array<{
    nodeId: string;
    slots: number[];
    openings: number;
    score: number;
}>;
/**
 * Format seconds as HH:MM:SS or MM:SS.
 * @param {number} sec
 * @returns {string}
 */
export function formatHMS(sec: number): string;
/**
 * Format a Date or timestamp as "HH:MM:SS UTC".
 * @param {Date|number|string} dt
 * @returns {string}
 */
export function formatUTC(dt: Date | number | string): string;
/**
 * Store a session plan on the server.
 * @param {object} cfg       LTX plan config
 * @param {string} [apiBase] API base URL (default: interplanet.live)
 * @returns {Promise<{plan_id:string, segments:object[], total_min:number, stored:boolean}>}
 */
export function storeSession(cfg: object, apiBase?: string): Promise<{
    plan_id: string;
    segments: object[];
    total_min: number;
    stored: boolean;
}>;
/**
 * Retrieve a stored session plan by plan ID.
 * @param {string} planId
 * @param {string} [apiBase]
 * @returns {Promise<{plan_id:string, plan:object, created_at:string, views:number}>}
 */
export function getSession(planId: string, apiBase?: string): Promise<{
    plan_id: string;
    plan: object;
    created_at: string;
    views: number;
}>;
/**
 * Download ICS content for a stored plan from the server.
 * @param {string} planId
 * @param {{start:string, duration_min:number}} opts
 * @param {string} [apiBase]
 * @returns {Promise<string>} ICS text
 */
export function downloadICS(planId: string, opts: {
    start: string;
    duration_min: number;
}, apiBase?: string): Promise<string>;
/**
 * Submit session feedback.
 * @param {object} payload
 * @param {string} [apiBase]
 * @returns {Promise<{ok:boolean, feedback_id:number}>}
 */
export function submitFeedback(payload: object, apiBase?: string): Promise<{
    ok: boolean;
    feedback_id: number;
}>;
/**
 * Canonical JSON serialisation (RFC 8785 / JCS).
 * Recursively sorts object keys lexicographically (Unicode code-point order).
 * Arrays preserve element order. No optional whitespace.
 *
 * @param {*} obj  Any JSON-serialisable value
 * @returns {string}
 */
export function canonicalJSON(obj: any): string;
/**
 * Generate a new Node Identity Key (NIK) record.
 * Uses Ed25519 via Node.js built-in node:crypto.
 *
 * @param {object}  [options]
 * @param {number}  [options.validDays=365]  Key validity period in days
 * @param {string}  [options.nodeLabel='']   Optional human-readable label
 * @returns {{ nik: object, privateKeyB64: string }}
 */
export function generateNIK(options?: {
    validDays?: number | undefined;
    nodeLabel?: string | undefined;
}): {
    nik: object;
    privateKeyB64: string;
};
/**
 * Return the full SHA-256 hex fingerprint of a NIK's public key.
 * @param {{ publicKey: string }} nik
 * @returns {string}  64-character lowercase hex string
 */
export function nikFingerprint(nik: {
    publicKey: string;
}): string;
/**
 * Returns true if the NIK's validUntil timestamp is in the past.
 * @param {{ validUntil: string }} nik
 * @returns {boolean}
 */
export function isNIKExpired(nik: {
    validUntil: string;
}): boolean;
/**
 * Sign an LTX session plan using a simplified COSE_Sign1-compatible structure.
 * Uses Ed25519 via Node.js node:crypto.
 *
 * Wire format (JSON envelope):
 *   { plan, coseSign1: { protected, unprotected: { kid }, payload, signature } }
 * All binary fields are base64url strings (no padding).
 *
 * @param {object} plan           LTX plan config
 * @param {string} privateKeyB64  Base64url-encoded raw 32-byte Ed25519 private seed
 * @returns {{ plan: object, coseSign1: object }}
 */
export function signPlan(plan: object, privateKeyB64: string): {
    plan: object;
    coseSign1: object;
};
/**
 * Verify a COSE_Sign1-signed session plan envelope.
 *
 * @param {{ plan: object, coseSign1: object }} coseEnvelope  Output from signPlan()
 * @param {Map<string, object>|object} keyCache               Map or plain object of nodeId → NIK
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyPlan(coseEnvelope: {
    plan: object;
    coseSign1: object;
}, keyCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
/**
 * Create a signed KEY_BUNDLE message containing all node NIKs.
 *
 * @param {string}   planId             Plan identifier
 * @param {object[]} nikArray           Array of NIK records to bundle
 * @param {string}   hostPrivateKeyB64  Base64url-encoded host private key seed
 * @param {object}   [freshness]        Global-scope freshness fields (Story 70.4,
 *                                      LTX-SECURITY.md §11.1): { senderNodeId, seq,
 *                                      issuedAt? }. When present, issuedAt and seq
 *                                      are covered by bundleSig; legacy bundles
 *                                      without them sign the keys array only.
 * @returns {object} KEY_BUNDLE message with bundleSig
 */
export function createKeyBundle(planId: string, nikArray: object[], hostPrivateKeyB64: string, freshness?: object): object;
/**
 * Verify a KEY_BUNDLE signature against a bootstrap NIK and return a populated KeyCache.
 * Expired NIKs are excluded from the cache.
 *
 * @param {object} keyBundle     KEY_BUNDLE message (from createKeyBundle)
 * @param {object} bootstrapNIK  NIK used to verify the bundle signature
 * @param {object} [freshness]   Global-scope freshness enforcement (Story 70.4,
 *                               LTX-SECURITY.md §11): { tracker, nowMs, maxAgeDays? }
 *                               where tracker is from createGlobalSequenceTracker().
 * @returns {Map<string, object>|null}  Map of nodeId → NIK, or null if invalid
 */
export function verifyAndCacheKeys(keyBundle: object, bootstrapNIK: object, freshness?: object): Map<string, object> | null;
/**
 * Create a signed KEY_REVOCATION message.
 *
 * @param {string} planId             Plan identifier
 * @param {string} revokedNodeId      nodeId of the key to revoke
 * @param {string} reason             Human-readable reason for revocation
 * @param {string} hostPrivateKeyB64  Base64url-encoded host private key seed
 * @returns {object} KEY_REVOCATION message with revocationSig
 */
export function createRevocation(planId: string, revokedNodeId: string, reason: string, hostPrivateKeyB64: string): object;
/**
 * Apply a KEY_REVOCATION to a key cache, removing the revoked entry.
 *
 * @param {Map<string, object>} cache       Key cache (from verifyAndCacheKeys)
 * @param {object}              revocation  KEY_REVOCATION message
 * @returns {boolean}  true if revocation was applied, false if type mismatch
 */
export function applyRevocation(cache: Map<string, object>, revocation: object): boolean;
/**
 * Create a sequence tracker for a given plan.
 * Tracks both outbound (nextSeq) and inbound (recordSeq) sequence numbers
 * per nodeId, enabling monotonic-increment enforcement and replay rejection.
 *
 * Inbound seqs are checked against a sliding reorder window below the
 * highest seq seen (the high-water mark). Seqs skipped by a gap are
 * remembered while they remain inside the window, so a delayed but genuine
 * bundle that arrives after a higher seq is accepted and flagged late,
 * while an exact duplicate of an already-accepted (nodeId, seq) is rejected
 * as a replay. Seqs below the window are rejected as replays (they cannot be
 * distinguished from one). Missing-seq markers live in the storage adapter,
 * so the window survives restarts when the adapter is persistent.
 *
 * @param {string} planId   Plan identifier used to namespace storage keys
 * @param {object} [storage] Optional storage adapter with get(key)/set(key,val)
 *                           and optional delete(key)
 * @param {object} [options]
 * @param {number} [options.reorderWindow=SEQ_REORDER_WINDOW]  0 disables late acceptance
 * @returns {object} Sequence tracker instance
 */
export function createSequenceTracker(planId: string, storage?: object, options?: {
    reorderWindow?: number | undefined;
}): object;
/**
 * Default reorder window for inbound seqs (LTX-SECURITY.md §11.2): a seq up to
 * this far below the highest seen, never seen before, is accepted as 'late'.
 */
export const SEQ_REORDER_WINDOW: 64;
/**
 * Add a seq field to a bundle object using the tracker's next sequence number.
 * @param {object} bundle       Bundle object to stamp
 * @param {object} tracker      Sequence tracker (from createSequenceTracker)
 * @param {string} nodeId       Sending node ID
 * @returns {object}  New bundle with seq field added
 */
export function addSeq(bundle: object, tracker: object, nodeId: string): object;
/**
 * Check an incoming bundle's seq field against the tracker.
 * @param {object} bundle         Incoming bundle (must have .seq)
 * @param {object} tracker        Sequence tracker (from createSequenceTracker)
 * @param {string} senderNodeId   Node ID of the sender
 * @returns {{ accepted: boolean, gap: boolean, gapSize: number, late?: boolean, reason?: string }}
 */
export function checkSeq(bundle: object, tracker: object, senderNodeId: string): {
    accepted: boolean;
    gap: boolean;
    gapSize: number;
    late?: boolean;
    reason?: string;
};
/**
 * Create a global-scope sequence tracker keyed (senderNodeId, msgType).
 * Session-independent bundles (KEY_BUNDLE, KEY_REVOCATION, release manifests)
 * exist outside any planId; this scope closes cross-session replay.
 *
 * @param {object} [storage]  Optional storage adapter with get(key)/set(key,val)
 * @returns {object} Global sequence tracker instance
 */
export function createGlobalSequenceTracker(storage?: object): object;
/**
 * Enforce the issuedAt max-age window for global-scope bundles
 * (LTX-SECURITY.md §11.2). `nowMs` is injected for determinism.
 *
 * @param {string} issuedAt  ISO 8601 timestamp from the bundle
 * @param {{ nowMs: number, maxAgeDays?: number }} opts
 * @returns {{ accepted: boolean, reason?: string }}
 */
export function checkIssuedAt(issuedAt: string, opts: {
    nowMs: number;
    maxAgeDays?: number;
}): {
    accepted: boolean;
    reason?: string;
};
/** Default issuedAt max age: 30 days (exceeds the longest conjunction blackout). */
export const ISSUED_AT_MAX_AGE_DAYS: 30;
/**
 * Create an RFC 9162-compatible Merkle audit log.
 *
 * Leaf hash:  SHA-256(0x00 || entry_bytes)
 * Node hash:  SHA-256(0x01 || left || right)
 * Empty root: 32 zero bytes
 *
 * @returns {object} Log instance with append/proof/consistency/sign operations
 */
export function createMerkleLog(): object;
/**
 * Verify a signed tree head produced by log.signTreeHead().
 * @param {object} signedHead  Output from signTreeHead()
 * @param {object} nik         NIK record with publicKey
 * @returns {boolean}
 */
export function verifyTreeHead(signedHead: object, nik: object): boolean;
/**
 * Add a BPSec Bundle Integrity Block (Context ID 1, RFC 9173) to a bundle.
 * Computes HMAC-SHA-256 over canonicalJSON of the bundle (with any existing
 * bib field stripped) and returns a new bundle object with a bib field added.
 * Does NOT mutate the input bundle.
 *
 * @param {object} bundle       Any LTX message bundle (plain JS object)
 * @param {string} hmacKeyB64   Base64url-encoded raw 32-byte HMAC-SHA-256 key
 * @returns {object}  New bundle: { ...bundleWithoutBib, bib: { contextId, targetBlockNumber, hmac } }
 */
export function addBIB(bundle: object, hmacKeyB64: string): object;
/**
 * Verify a BPSec Bundle Integrity Block (Context ID 1, RFC 9173).
 * Extracts the bib field, recomputes HMAC-SHA-256 over canonicalJSON of the
 * remaining bundle fields, and compares with bib.hmac.
 *
 * @param {object} bundle       Bundle object (must contain a bib field)
 * @param {string} hmacKeyB64   Base64url-encoded raw 32-byte HMAC-SHA-256 key
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyBIB(bundle: object, hmacKeyB64: string): {
    valid: boolean;
    reason?: string;
};
/**
 * Generate a fresh base64url-encoded 32-byte random key suitable for use
 * as an HMAC-SHA-256 Bundle Integrity Block key.
 *
 * @returns {string}  Base64url-encoded 32-byte key (43 characters, no padding)
 */
export function generateBIBKey(): string;
/**
 * Add an LTX-native Ed25519 BIB (LTX-SECURITY.md §8.2): the bundle is signed
 * with the originating node's NIK, giving per-bundle non-repudiation without
 * a pre-shared pairwise key. The input bundle is not mutated.
 *
 * @param {object} bundle         Any LTX message bundle (plain JS object)
 * @param {string} privateKeyB64  Base64url-encoded raw 32-byte Ed25519 private seed
 * @returns {object}  New bundle: { ...bundleWithoutBib, bib: { securityContext, targetBlockNumber, sig } }
 */
export function addBIBEd25519(bundle: object, privateKeyB64: string): object;
/**
 * Verify an LTX-native Ed25519 BIB against the sender's NIK.
 * Rejects HMAC-context BIBs (context-confusion defence).
 *
 * @param {object} bundle  Bundle containing an Ed25519 bib field
 * @param {object} nik     Sender's NIK record with publicKey
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyBIBEd25519(bundle: object, nik: object): {
    valid: boolean;
    reason?: string;
};
/**
 * Create an Emergency Override Key (EOK).
 * Same structure as a NIK but with keyType: 'eok'.
 *
 * @param {object}  [options]
 * @param {number}  [options.validDays=30]  Key validity period in days (default: 30)
 * @param {string}  [options.nodeLabel='']  Optional human-readable label
 * @returns {{ eok: object, privateKey: string }}
 */
export function createEOK(options?: {
    validDays?: number | undefined;
    nodeLabel?: string | undefined;
}): {
    eok: object;
    privateKey: string;
};
/**
 * Create a signed EMERGENCY_OVERRIDE bundle.
 *
 * @param {string} planId             Plan identifier
 * @param {string} action             Action to override (e.g. 'ABORT', 'EXTEND')
 * @param {string} eokPrivateKeyB64   Base64url-encoded raw 32-byte Ed25519 private seed
 * @param {string} eokId              ID of the EOK (from createEOK)
 * @returns {object} EMERGENCY_OVERRIDE bundle with overrideSig
 */
export function createEmergencyOverride(planId: string, action: string, eokPrivateKeyB64: string, eokId: string): object;
/**
 * Verify an EMERGENCY_OVERRIDE bundle against an EOK cache.
 *
 * @param {object}                  overrideBundle  Output from createEmergencyOverride()
 * @param {Map<string,object>|object} eokCache       Map or plain object of eokId → eok
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyEmergencyOverride(overrideBundle: object, eokCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
/**
 * Create an ACTION_COSIG bundle for multi-person authorisation.
 *
 * @param {string} entryId           Entry identifier to co-sign
 * @param {string} planId            Plan identifier
 * @param {string} cosigNodeId       Node ID of the co-signer
 * @param {string} cosigPrivateKeyB64 Base64url-encoded raw 32-byte Ed25519 private seed
 * @param {object} cosigNIK          NIK of the co-signer (used for cosigNodeId derivation)
 * @returns {object} ACTION_COSIG bundle with cosigSig
 */
export function createCoSig(entryId: string, planId: string, cosigNodeId: string, cosigPrivateKeyB64: string, cosigNIK: object): object;
/**
 * Check multi-person authorisation by verifying co-signature bundles.
 *
 * @param {object[]}                    cosigBundles   Array of ACTION_COSIG bundles
 * @param {string}                      entryId        Entry identifier to match
 * @param {string}                      planId         Plan identifier to match
 * @param {Map<string,object>|object}   keyCache       Map or plain object of nodeId → NIK
 * @param {number}                      requiredCount  Minimum valid signatures required
 * @returns {{ authorised: boolean, validSigCount: number, invalidCount: number }}
 */
export function checkMultiAuth(cosigBundles: object[], entryId: string, planId: string, keyCache: Map<string, object> | object, requiredCount: number): {
    authorised: boolean;
    validSigCount: number;
    invalidCount: number;
};
/**
 * Create a signed CONJUNCTION_CHECKPOINT bundle.
 * Captures Merkle root, tree size, and last sequence numbers at the start
 * of a communication blackout (conjunction) period.
 *
 * @param {string} planId              Plan identifier
 * @param {string} signerNodeId        Node ID of the signer (from nik.nodeId)
 * @param {{ conjunctionStart: string, conjunctionEnd: string }} conjunctionInfo
 * @param {string} merkleRoot          Hex string from merkleLog.rootHex()
 * @param {number} treeSize            Number from merkleLog.treeSize()
 * @param {object} lastSeqPerNode      Plain object { nodeId: lastSeenSeq, ... }
 * @param {string} privateKeyB64       Base64url raw 32-byte Ed25519 seed
 * @returns {object} Complete CONJUNCTION_CHECKPOINT bundle
 */
export function createConjunctionCheckpoint(planId: string, signerNodeId: string, conjunctionInfo: {
    conjunctionStart: string;
    conjunctionEnd: string;
}, merkleRoot: string, treeSize: number, lastSeqPerNode: object, privateKeyB64: string): object;
/**
 * Verify a CONJUNCTION_CHECKPOINT bundle.
 *
 * @param {object} checkpoint          CONJUNCTION_CHECKPOINT bundle
 * @param {Map<string,object>|object} keyCache  nodeId → NIK
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyConjunctionCheckpoint(checkpoint: object, keyCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
/**
 * Create a post-conjunction queue for holding bundles during a blackout period.
 * Bundles queued during the conjunction are processed via drain() after contact resumes.
 *
 * @returns {{ enqueue, size, drain, getQueue }}
 */
export function createPostConjunctionQueue(): {
    enqueue: any;
    size: any;
    drain: any;
    getQueue: any;
};
/**
 * Create a signed POST_CONJUNCTION_CLEAR bundle.
 * Signals that the conjunction period has ended and queued bundles have been processed.
 *
 * @param {string} planId          Plan identifier
 * @param {number} queueProcessed  Number of queued bundles that were processed
 * @param {string} privateKeyB64   Base64url raw 32-byte Ed25519 seed
 * @returns {object} Complete POST_CONJUNCTION_CLEAR bundle
 */
export function createPostConjunctionClear(planId: string, queueProcessed: number, privateKeyB64: string): object;
/**
 * Verify a POST_CONJUNCTION_CLEAR bundle.
 * Since the clear bundle has no signer ID field, tries each NIK in the cache.
 *
 * @param {object} clearBundle                     POST_CONJUNCTION_CLEAR bundle
 * @param {Map<string,object>|object} keyCache      nodeId → NIK
 * @returns {{ valid: boolean, signerNodeId?: string, reason?: string }}
 */
export function verifyPostConjunctionClear(clearBundle: object, keyCache: Map<string, object> | object): {
    valid: boolean;
    signerNodeId?: string;
    reason?: string;
};
/**
 * Compute the SHA-256 hex digest of a string or Buffer.
 * Helper for computing artefact hashes before including in a manifest.
 *
 * @param {string|Buffer} data
 * @returns {string}  64-character lowercase hex string
 */
export function artefactSha256(data: string | Uint8Array): string;
/**
 * Create a signed WINDOW_MANIFEST for a set of artefacts.
 * Uses hedged EdDSA: a random nonceSalt is included in the signed payload,
 * ensuring each call produces a unique signature even for identical inputs.
 *
 * @param {string}   planId         Plan identifier
 * @param {number}   windowSeq      Window sequence number
 * @param {Array<{name:string, sha256:string, sizeBytes:number}>} artefacts
 * @param {object}   treeHead       Signed tree head from merkleLog.signTreeHead()
 * @param {string}   privateKeyB64  Base64url-encoded raw 32-byte Ed25519 private seed
 * @returns {object} WINDOW_MANIFEST with manifestSig
 */
export function createWindowManifest(planId: string, windowSeq: number, artefacts: Array<{
    name: string;
    sha256: string;
    sizeBytes: number;
}>, treeHead: object, privateKeyB64: string): object;
/**
 * Verify a WINDOW_MANIFEST signature against a key cache.
 *
 * @param {object}                  manifest   WINDOW_MANIFEST (from createWindowManifest)
 * @param {Map<string,object>|object} keyCache  Map or plain object of nodeId → NIK
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyWindowManifest(manifest: object, keyCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
/**
 * Hedged EdDSA signing: signs dataBytes with a random nonceSalt included in the payload.
 * Produces a unique signature per call even for identical inputs.
 *
 * @param {Buffer} dataBytes      Data to sign
 * @param {string} privateKeyB64  Base64url-encoded raw 32-byte Ed25519 private seed
 * @returns {{ signature: string, nonceSalt: string }}
 */
export function hedgedSign(dataBytes: Uint8Array, privateKeyB64: string): {
    signature: string;
    nonceSalt: string;
};
/**
 * Verify a hedged EdDSA signature produced by hedgedSign().
 *
 * @param {Buffer} dataBytes      Original data that was signed
 * @param {string} signature      Base64url-encoded Ed25519 signature
 * @param {string} nonceSalt      Base64url-encoded nonce salt (from hedgedSign result)
 * @param {string} publicKeyB64   Base64url-encoded raw 32-byte Ed25519 public key
 * @returns {boolean}
 */
export function hedgedVerify(dataBytes: Uint8Array, signature: string, nonceSalt: string, publicKeyB64: string): boolean;
/**
 * Generate a fresh 32-byte AES-256 session key.
 * @returns {Buffer} 32 random bytes
 */
export function generateSessionKey(): Uint8Array;
/**
 * Encrypt a payload object using AES-256-GCM (BPSec BCB).
 * Returns a BCB bundle with base64url-encoded nonce, ciphertext, and auth tag.
 *
 * @param {object} payload      Plain JS object to encrypt (will be JSON-serialised)
 * @param {Buffer} sessionKey   32-byte AES-256 key (from generateSessionKey)
 * @returns {{ type: 'BCB', nonce: string, ciphertext: string, tag: string }}
 */
export function encryptWindow(payload: object, sessionKey: Uint8Array): {
    type: "BCB";
    nonce: string;
    ciphertext: string;
    tag: string;
};
/**
 * Decrypt a BCB bundle using AES-256-GCM.
 * Verifies the AEAD authentication tag; returns { valid: false } on failure.
 *
 * @param {object} bundle       BCB bundle ({ type, nonce, ciphertext, tag })
 * @param {Buffer} sessionKey   32-byte AES-256 key
 * @returns {{ valid: boolean, plaintext?: object, reason?: string }}
 */
export function decryptWindow(bundle: object, sessionKey: Uint8Array): {
    valid: boolean;
    plaintext?: object;
    reason?: string;
};
/**
 * Generate an Ed25519 Release Signing Key (RSK) pair.
 * Returns base64url-encoded PKCS8 DER private key and SPKI DER public key.
 *
 * @returns {{ privateKeyB64: string, publicKeyB64: string }}
 */
export function generateRSK(): {
    privateKeyB64: string;
    publicKeyB64: string;
};
/**
 * Create a signed release manifest for a package.
 *
 * @param {string}   packageName     Package name (e.g. 'ltx-sdk')
 * @param {string}   version         Version string (e.g. '1.0.0')
 * @param {Array<{ path: string, content: Buffer }>} files  Files to include in manifest
 * @param {string}   privateKeyB64   Base64url-encoded PKCS8 DER Ed25519 private key (from generateRSK)
 * @returns {object} Signed manifest object with manifestSig field
 */
export function createManifest(packageName: string, version: string, files: Array<{
    path: string;
    content: Uint8Array;
}>, privateKeyB64: string): object;
/**
 * Verify a signed release manifest.
 *
 * @param {object} manifest       Manifest object (from createManifest)
 * @param {string} rskPublicKey   Base64url-encoded SPKI DER Ed25519 public key (from generateRSK)
 * @returns {{ valid: boolean, files?: Array, reason?: string }}
 */
export function verifyManifest(manifest: object, rskPublicKey: string): {
    valid: boolean;
    files?: any[];
    reason?: string;
};
/**
 * Create a session context in DRAFT state.
 * @param {object} plan     v2/v3 plan config
 * @param {string} planId   makePlanId(plan) — supplied so this stays pure
 * @param {object} [options]  { quorum: 'all' | 'majority' | number }
 * @throws {Error} err.code 'reserved_streams' | 'reserved_branching' (§3.5, §7)
 */
export function createSession(plan: object, planId: string, options?: object): {
    state: string;
    plan: object;
    planId: string;
    sessionRootPlanId: string;
    planVersion: any;
    lock: null;
    lockStartedAtMs: null;
    lockTimeoutMs: number;
    confirmations: {};
    mismatched: never[];
    quorumThreshold: any;
    subset: null;
    degradedReasons: never[];
    resumeState: null;
    pendingAmendment: null;
};
/**
 * Advance the session state machine (pure).
 * @param {object} ctx    Session context from createSession()/transition()
 * @param {object} event  { type, nowMs, ... }
 * @returns {{ctx: object, effects: object[]}}
 */
export function transition(ctx: object, event: object): {
    ctx: object;
    effects: object[];
};
/** 2 × one-way delay to the furthest node, in ms (§5.1). */
export function lockTimeoutMs(plan: any): number;
/** SHA-256 hex of the RFC 8785 canonical JSON of a plan. */
export function planHash(plan: any): any;
/**
 * Create a signed amendment of signedPlan with `changes` applied.
 * Successor is always v3: planVersion+1, prevPlanHash = SHA-256(canonicalJSON
 * of predecessor) — never the legacy v2 polynomial hash (LTX-SECURITY §7.6).
 * Throws (err.code 'reserved_streams' | 'reserved_branching') if the successor
 * would carry reserved fields (§3.5, §7).
 */
export function createAmendment(signedPlan: any, changes: any, privateKeyB64: any): {
    plan: object;
    coseSign1: object;
};
/**
 * Verify an amendment chain: chain[0] is the root, each later element a
 * successive amendment (signature, planVersion +1, prevPlanHash match).
 */
export function verifyAmendmentChain(chain: any, keyCache: any): {
    valid: boolean;
    reason: string;
} | {
    valid: boolean;
    reason?: undefined;
};
/**
 * §6.2 drift response: amend by inserting a BUFFER segment after segment
 * index afterIndex (append with -1). Elapsed segments must not be touched.
 */
export function insertBufferViaAmendment(signedPlan: any, options: any, privateKeyB64: any): {
    plan: object;
    coseSign1: object;
};
/**
 * Create a signed register entry (LTX-SECURITY.md §9.5).
 * @param {string} type     One of ENTRY_PREFIX keys
 * @param {object} content
 * @param {object} opts     { sessionId, nodeId, seq, timestamp, privateKeyB64, entryId? }
 */
export function createRegisterEntry(type: string, content: object, opts: object): {
    entryId: any;
    sessionId: any;
    nodeId: any;
    seq: any;
    type: string;
    content: object;
    timestamp: any;
} & {
    sig: any;
};
/** Verify a register entry against keyCache[entry.nodeId] → NIK. */
export function verifyRegisterEntry(entry: any, keyCache: any): {
    valid: boolean;
    reason: string;
} | {
    valid: boolean;
    reason?: undefined;
};
/** Total order (timestamp, nodeId, seq) — LTX-SPECIFICATION.md §8.2. */
export function compareEntries(a: any, b: any): number;
/** De-duplicate by (nodeId, seq) and sort into the §8.2 total order. */
export function orderEntries(entries: any): any[];
/** Reduce question register state (LTX-SPECIFICATION.md §9.4). Pure. */
export function reduceQuestions(entries: any): {
    byId: {};
    superseded: any[];
};
/** Reduce action register state (LTX-SPECIFICATION.md §10.2). Pure. */
export function reduceActions(entries: any): {
    byId: {};
    superseded: any[];
};
/**
 * Reduce decision register state (LTX-SPECIFICATION.md §10.3). Pure.
 * `decision` entries record a decision (did = entryId, version 1);
 * `decision_update` entries reference content.did and revise text/rationale
 * or rescind it. Conflicts follow §8.2 exactly as for questions and actions:
 * higher object version wins, then the lowest editor nodeId; losers are
 * returned in `superseded`.
 */
export function reduceDecisions(entries: any): {
    byId: {};
    superseded: any[];
};
/** Re-emit v3 plan question seeds as signed log entries at lock (§9.2). */
export function emitQuestionSeeds(seeds: any, opts: any): any;
/**
 * Deterministic merge of two entry logs (§8.2): verify, union de-duplicated
 * by (nodeId, seq), order totally. Symmetric by construction.
 */
export function mergeLogs(entriesA: any, entriesB: any, keyCache: any): {
    entries: any[];
    rejected: {
        entry: any;
        reason: string;
    }[];
};
/** Merkle root over an ordered entry list (leaves in log order). */
export function entriesRoot(entries: any): any;
/** MERGE segment (§8.4): merge + HOST-signed merge_snapshot entry. */
export function runMergeSegment(localEntries: any, remoteEntries: any, keyCache: any, opts: any): {
    merged: {
        entries: any[];
        rejected: {
            entry: any;
            reason: string;
        }[];
    };
    snapshot: {
        entryId: any;
        sessionId: any;
        nodeId: any;
        seq: any;
        type: string;
        content: object;
        timestamp: any;
    } & {
        sig: any;
    };
};
/**
 * Partition recovery (§8.3 / LTX-SECURITY §9.4): verify remote tree head,
 * accept verified prefix extension, else deterministic merge, else flag
 * divergence.
 */
export function recoverPartition(localEntries: any, remoteEntries: any, remoteHead: any, remoteNik: any, keyCache: any): {
    action: string;
    reason: string;
    entries?: undefined;
    rejected?: undefined;
} | {
    action: string;
    entries: any;
    reason?: undefined;
    rejected?: undefined;
} | {
    action: string;
    entries: any[];
    rejected: {
        entry: any;
        reason: string;
    }[];
    reason?: undefined;
};
/** Tagged value wrapper (major type 6). */
export class CborTag {
    constructor(tag: any, value: any);
    tag: any;
    value: any;
}
/**
 * Encode a value to deterministic CBOR bytes.
 * Floats are rejected (integers only); map keys sort bytewise by encoded form.
 *
 * @param {*} value  Value to encode (see supported types above)
 * @returns {Buffer}
 */
export function encodeCbor(value: any): Uint8Array;
/**
 * Decode deterministic CBOR bytes to a value (maps decode to Map).
 * Byte-string map keys decode to base64url strings; trailing bytes rejected.
 *
 * @param {Uint8Array|Buffer} bytes
 * @returns {*}
 */
export function decodeCbor(bytes: Uint8Array): any;
export const COSE_SIGN1_TAG: 18;
export const COSE_ALG_ED25519: -19;
/**
 * Sign a plan as a real CBOR COSE_Sign1 (tag 18). The kid (header label 4)
 * is the signer's NIK nodeId — base64url of the first 16 bytes of
 * SHA-256(raw public key), matching generateNIK()/signPlan().
 *
 * @param {object} plan           LTX plan config
 * @param {string} privateKeyB64  Base64url-encoded raw 32-byte Ed25519 private seed
 * @returns {{ plan: object, coseSign1CborB64: string }}
 */
export function signPlanCose(plan: object, privateKeyB64: string): {
    plan: object;
    coseSign1CborB64: string;
};
/**
 * Verify a CBOR COSE_Sign1 plan envelope against the key cache.
 * Rejects non-Ed25519 algorithms (including the deprecated -8) and payloads
 * that do not match the accompanying plan object.
 *
 * @param {{ plan: object, coseSign1CborB64: string }} envelope  Output from signPlanCose()
 * @param {Map<string,object>|object} keyCache                  nodeId → NIK
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyPlanCose(envelope: {
    plan: object;
    coseSign1CborB64: string;
}, keyCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
/**
 * Verify either envelope form: the CBOR COSE_Sign1 (coseSign1CborB64) or the
 * frozen TRANSITIONAL JSON envelope (coseSign1) — LTX-SECURITY.md §7.5.
 *
 * @param {object} envelope                     Output from signPlanCose() or signPlan()
 * @param {Map<string,object>|object} keyCache  nodeId → NIK
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifyPlanAny(envelope: object, keyCache: Map<string, object> | object): {
    valid: boolean;
    reason?: string;
};
