/**
 * @interplanet/ltx — ICS generation
 */

import { upgradeConfig }   from './plan.js';
import { computeSegments } from './segments.js';
import { makePlanId }      from './segments.js';
import type { LtxPlan, LtxPlanV1 } from './types.js';

function _fmtDT(dt: Date): string {
  return dt.toISOString().replace(/[-:.]/g, '').slice(0, 15) + 'Z';
}

function _toId(name: string): string {
  return name.replace(/\s+/g, '-').toUpperCase();
}

/**
 * Generate LTX-extended iCalendar (.ics) content for a plan.
 * Includes `LTX-NODE`, `LTX-DELAY`, `LTX-LOCALTIME` extension properties.
 */
export function generateICS(cfg: LtxPlan | LtxPlanV1): string {
  const c        = upgradeConfig(cfg);
  const segs     = computeSegments(c);
  const start    = new Date(c.start);
  const end      = segs[segs.length - 1].end;
  const planId   = makePlanId(c);
  const nodes    = c.nodes || [];
  const host     = nodes[0] || { name: 'Earth HQ', role: 'HOST' as const, delay: 0, location: 'earth', id: 'N0' };
  const parts    = nodes.slice(1);
  const segTpl   = c.segments.map(s => s.type).join(',');

  const nodeLines  = nodes.map(n => `LTX-NODE:ID=${_toId(n.name)};ROLE=${n.role}`);
  const delayLines = parts.map(n => {
    const d = n.delay || 0;
    return `LTX-DELAY;NODEID=${_toId(n.name)}:ONEWAY-MIN=${d};ONEWAY-MAX=${d + 120};ONEWAY-ASSUMED=${d}`;
  });
  const localLines = nodes
    .filter(n => n.location === 'mars')
    .map(n => `LTX-LOCALTIME:NODE=${_toId(n.name)};SCHEME=LMST;PARAMS=LONGITUDE:0E`);

  const partNames  = parts.map(p => p.name).join(', ') || 'remote nodes';
  const delayDesc  = parts.length
    ? parts.map(p => `${p.name}: ${Math.round((p.delay || 0) / 60)} min one-way`).join(' · ')
    : 'no participant delay configured';

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//InterPlanet//LTX v1.1//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${planId}@interplanet.live`,
    `DTSTAMP:${_fmtDT(new Date())}`,
    `DTSTART:${_fmtDT(start)}`,
    `DTEND:${_fmtDT(end)}`,
    `SUMMARY:${c.title}`,
    `DESCRIPTION:LTX session — ${host.name} with ${partNames}\\n` +
      `Signal delays: ${delayDesc}\\n` +
      `Mode: ${c.mode} · Segment plan: ${segTpl}\\n` +
      `Generated by InterPlanet (https://interplanet.live)`,
    `LTX:1`,
    `LTX-PLANID:${planId}`,
    `LTX-QUANTUM:PT${c.quantum}M`,
    `LTX-SEGMENT-TEMPLATE:${segTpl}`,
    `LTX-MODE:${c.mode}`,
    ...nodeLines,
    ...delayLines,
    `LTX-READINESS:CHECK=PT10M;REQUIRED=TRUE;FALLBACK=LTX-RELAY`,
    ...localLines,
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}
