/**
 * @interplanet/ltx — ICS generation
 * Story 71.3 — optional per-attendee export (LTX-SPECIFICATION.md §14.5)
 */

import { upgradeConfig }   from './plan.js';
import { computeSegments, computeSegmentsFor } from './segments.js';
import { makePlanId }      from './segments.js';
import type { AnyLtxPlan, LtxPlan, LtxPlanV1 } from './types.js';

/** Options for generateICS(). */
export interface GenerateICSOptions {
  /**
   * Per-attendee export: one VEVENT per segment at this viewer's local
   * arrival times (attributed segments shift by pairDelay(speaker, viewer)).
   * Omit for the default single-VEVENT HOST-frame export.
   */
  viewerNodeId?: string;
}

function _fmtDT(dt: Date): string {
  return dt.toISOString().replace(/[-:.]/g, '').slice(0, 15) + 'Z';
}

function _toId(name: string): string {
  return name.replace(/\s+/g, '-').toUpperCase();
}

/**
 * Generate LTX-extended iCalendar (.ics) content for a plan.
 * Includes `LTX-NODE`, `LTX-DELAY`, `LTX-LOCALTIME` extension properties.
 * With `options.viewerNodeId`, emits the per-attendee form (§14.5).
 */
export function generateICS(
  cfg: LtxPlan | LtxPlanV1 | AnyLtxPlan,
  options: GenerateICSOptions = {},
): string {
  if (options.viewerNodeId) return _generateViewerICS(cfg, options.viewerNodeId);
  const c        = upgradeConfig(cfg as LtxPlan | LtxPlanV1);
  const segs     = computeSegments(c);
  const start    = new Date(c.start);
  const end      = segs[segs.length - 1].end;
  const planId   = makePlanId(c);
  const nodes    = c.nodes || [];
  const host     = nodes[0] || { name: 'Earth HQ', role: 'HOST' as const, delay: 0, location: 'earth', id: 'N0' };
  const parts    = nodes.slice(1);
  const segTpl   = c.segments.map(s => s.type).join(',');

  const nodeLines  = nodes.map(n => `LTX-NODE:ID=${_toId(n.name)};ROLE=${n.role}`);
  const delayLines = parts.map(n => {
    const d = n.delay || 0;
    return `LTX-DELAY;NODEID=${_toId(n.name)}:ONEWAY-MIN=${d};ONEWAY-MAX=${d + 120};ONEWAY-ASSUMED=${d}`;
  });
  const localLines = nodes
    .filter(n => n.location === 'mars')
    .map(n => `LTX-LOCALTIME:NODE=${_toId(n.name)};SCHEME=LMST;PARAMS=LONGITUDE:0E`);

  const partNames  = parts.map(p => p.name).join(', ') || 'remote nodes';
  const delayDesc  = parts.length
    ? parts.map(p => `${p.name}: ${Math.round((p.delay || 0) / 60)} min one-way`).join(' · ')
    : 'no participant delay configured';

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//InterPlanet//LTX v1.1//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${planId}@interplanet.live`,
    `DTSTAMP:${_fmtDT(new Date())}`,
    `DTSTART:${_fmtDT(start)}`,
    `DTEND:${_fmtDT(end)}`,
    `SUMMARY:${c.title}`,
    `DESCRIPTION:LTX session — ${host.name} with ${partNames}\\n` +
      `Signal delays: ${delayDesc}\\n` +
      `Mode: ${c.mode} · Segment plan: ${segTpl}\\n` +
      `Generated by InterPlanet (https://interplanet.live)`,
    `LTX:1`,
    `LTX-PLANID:${planId}`,
    `LTX-QUANTUM:PT${c.quantum}M`,
    `LTX-SEGMENT-TEMPLATE:${segTpl}`,
    `LTX-MODE:${c.mode}`,
    ...nodeLines,
    ...delayLines,
    `LTX-READINESS:CHECK=PT10M;REQUIRED=TRUE;FALLBACK=LTX-RELAY`,
    ...localLines,
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

/** v3 pair-delay properties (LTX-SPECIFICATION.md §3.7.2, spec/ltx-spec.md §8.3). */
function _pairDelayLines(c: LtxPlan): string[] {
  const delays = (c as { delays?: Record<string, number> }).delays;
  if (!delays) return [];
  return Object.keys(delays).sort().map(
    pair => `LTX-DELAY;PAIR=${pair}:ONEWAY-ASSUMED=${delays[pair]}`,
  );
}

/**
 * Per-attendee export (§14.5): one VEVENT per segment at the viewer's local
 * arrival times. Attributed segments are shifted by pairDelay(speaker, viewer);
 * summaries name the speaker and agenda label.
 */
function _generateViewerICS(cfg: LtxPlan | LtxPlanV1 | AnyLtxPlan, viewerNodeId: string): string {
  const c      = upgradeConfig(cfg as LtxPlan | LtxPlanV1);
  const segs   = computeSegmentsFor(c, viewerNodeId);
  const planId = makePlanId(c);
  const nodes  = c.nodes || [];
  const viewer = nodes.find(n => n.id === viewerNodeId);
  const dtstamp = _fmtDT(new Date());
  const nameOf = (id: string) => nodes.find(n => n.id === id)?.name || id;

  const events = segs.map((seg, i) => {
    const base = seg.label || seg.type;
    let summary: string;
    if (seg.perspective === 'transmit') {
      summary = `${base} — you present`;
    } else if (seg.perspective === 'receive') {
      summary = `${base} — ${nameOf(seg.speaker as string)}, arriving after ${Math.round(seg.arrivalOffsetS / 60)} min light-time`;
    } else {
      summary = `${base} (${c.title})`;
    }
    return [
      'BEGIN:VEVENT',
      `UID:${planId}-${viewerNodeId}-${i}@interplanet.live`,
      `DTSTAMP:${dtstamp}`,
      `DTSTART:${_fmtDT(seg.start)}`,
      `DTEND:${_fmtDT(seg.end)}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:LTX ${seg.type} segment of "${c.title}" from the perspective of ${viewer?.name || viewerNodeId}`,
      'LTX:1',
      `LTX-PLANID:${planId}`,
      `LTX-VIEWER:${viewerNodeId}`,
      ...(seg.speaker ? [`LTX-SPEAKER:${seg.speaker}`] : []),
      'END:VEVENT',
    ].join('\r\n');
  });

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//InterPlanet//LTX v1.1//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    ...events,
    ..._pairDelayLines(c),
    'END:VCALENDAR',
  ].join('\r\n');
}
