/**
 * @interplanet/ltx — Segment computation and plan ID
 */

import { upgradeConfig } from './plan.js';
import type { LtxPlan, LtxPlanV1, LtxSegment } from './types.js';

/**
 * Compute the timed segment array for a plan config.
 * Each segment has `start`, `end` (Date objects), and `durMin`.
 */
export function computeSegments(cfg: LtxPlan | LtxPlanV1): LtxSegment[] {
  const c   = upgradeConfig(cfg);
  const qMs = c.quantum * 60 * 1000;
  let t = new Date(c.start).getTime();
  return c.segments.map(s => {
    const durMs = s.q * qMs;
    const seg: LtxSegment = {
      type:   s.type,
      q:      s.q,
      start:  new Date(t),
      end:    new Date(t + durMs),
      durMin: s.q * c.quantum,
    };
    t += durMs;
    return seg;
  });
}

/**
 * Total session duration in minutes.
 */
export function totalMin(cfg: LtxPlan | LtxPlanV1): number {
  const c = upgradeConfig(cfg);
  return c.segments.reduce((a, s) => a + s.q * c.quantum, 0);
}

/**
 * Compute the deterministic plan ID string.
 * Matches the ID generated by `ltx.html` and `api/ltx.php`.
 *
 * @example `"LTX-20260301-EARTHHQ-MARSHAR-v2-a3b2c1d0"`
 */
export function makePlanId(cfg: LtxPlan | LtxPlanV1): string {
  const c       = upgradeConfig(cfg);
  const date    = new Date(c.start).toISOString().slice(0, 10).replace(/-/g, '');
  const nodes   = c.nodes || [];
  const hostStr = (nodes[0]?.name || 'HOST').replace(/\s+/g, '').toUpperCase().slice(0, 8);
  const nodeStr = nodes.length > 1
    ? nodes.slice(1).map(n => n.name.replace(/\s+/g, '').toUpperCase().slice(0, 4)).join('-').slice(0, 16)
    : 'RX';

  // Simple 32-bit hash of the JSON — mirrors JS imul hash
  const raw = JSON.stringify(c);
  let h = 0;
  for (let i = 0; i < raw.length; i++) {
    h = Math.imul(31, h) + raw.charCodeAt(i) | 0;
  }
  const hash = (h >>> 0).toString(16).padStart(8, '0');
  return `LTX-${date}-${hostStr}-${nodeStr}-v2-${hash}`;
}
