/**
 * @interplanet/ltx — Segment computation and plan ID
 */

import * as nodeCrypto from 'node:crypto';

import { upgradeConfig } from './plan.js';
import { canonicalJSON } from './security.js';
import type { AnyLtxPlan, LtxPlan, LtxPlanV1, LtxSegment } from './types.js';

/**
 * Compute the timed segment array for a plan config.
 * Each segment has `start`, `end` (Date objects), and `durMin`.
 */
export function computeSegments(cfg: LtxPlan | LtxPlanV1): LtxSegment[] {
  const c   = upgradeConfig(cfg);
  const qMs = c.quantum * 60 * 1000;
  let t = new Date(c.start).getTime();
  return c.segments.map(s => {
    const durMs = s.q * qMs;
    const seg: LtxSegment = {
      type:   s.type,
      q:      s.q,
      start:  new Date(t),
      end:    new Date(t + durMs),
      durMin: s.q * c.quantum,
    };
    t += durMs;
    return seg;
  });
}

/**
 * Total session duration in minutes.
 */
export function totalMin(cfg: LtxPlan | LtxPlanV1): number {
  const c = upgradeConfig(cfg);
  return c.segments.reduce((a, s) => a + s.q * c.quantum, 0);
}

/**
 * One-way delay in seconds between two nodes (LTX-SPECIFICATION.md §3.7).
 * v3 pair matrix is authoritative where present; otherwise the conservative
 * fallback: HOST pairs use the node's declared delay, non-HOST pairs the sum
 * of both HOST-relative delays (a safe upper bound via the HOST vertex).
 */
export function pairDelay(
  cfg: LtxPlan | LtxPlanV1 | AnyLtxPlan,
  nodeIdA: string,
  nodeIdB: string,
): number {
  const c = upgradeConfig(cfg as LtxPlan | LtxPlanV1);
  if (nodeIdA === nodeIdB) return 0;
  const delays = (c as { delays?: Record<string, number> }).delays;
  const key = [nodeIdA, nodeIdB].sort().join('|');
  if (delays && typeof delays[key] === 'number') return delays[key];
  const a = c.nodes.find(n => n.id === nodeIdA);
  const b = c.nodes.find(n => n.id === nodeIdB);
  if (!a || !b) throw new Error(`pairDelay: unknown node ${!a ? nodeIdA : nodeIdB}`);
  const hostId = c.nodes[0].id;
  if (nodeIdA === hostId) return b.delay || 0;
  if (nodeIdB === hostId) return a.delay || 0;
  return (a.delay || 0) + (b.delay || 0);
}

/** A computed segment from a specific viewer's perspective (§14.3). */
export interface LtxViewerSegment extends LtxSegment {
  /** Presenting node id, when the segment is attributed. */
  speaker?: string;
  /** Agenda label, when present. */
  label?: string;
  /** 'transmit' (viewer presents), 'receive' (arrives after light-time), 'neutral'. */
  perspective: 'transmit' | 'receive' | 'neutral';
  /** Light-time shift applied to start/end, in seconds (0 unless receiving). */
  arrivalOffsetS: number;
}

/**
 * Compute the timed segment array from viewer V's perspective
 * (LTX-SPECIFICATION.md §14.3): a segment attributed to speaker S starts for
 * V at segStart + pairDelay(S, V). Unattributed segments keep their times.
 */
export function computeSegmentsFor(
  cfg: LtxPlan | LtxPlanV1 | AnyLtxPlan,
  viewerNodeId: string,
): LtxViewerSegment[] {
  const c = upgradeConfig(cfg as LtxPlan | LtxPlanV1);
  if (!c.nodes.some(n => n.id === viewerNodeId)) {
    throw new Error(`computeSegmentsFor: unknown viewer ${viewerNodeId}`);
  }
  const base = computeSegments(c);
  return base.map((seg, i) => {
    const tpl = c.segments[i];
    const speaker = tpl.speaker;
    if (!speaker || (tpl.type !== 'TX' && tpl.type !== 'SPEAK' as string)) {
      return {
        ...seg,
        ...(speaker ? { speaker } : {}),
        ...(tpl.label ? { label: tpl.label } : {}),
        perspective: 'neutral' as const,
        arrivalOffsetS: 0,
      };
    }
    if (speaker === viewerNodeId) {
      return {
        ...seg, speaker,
        ...(tpl.label ? { label: tpl.label } : {}),
        perspective: 'transmit' as const,
        arrivalOffsetS: 0,
      };
    }
    const shiftS = pairDelay(c, speaker, viewerNodeId);
    return {
      ...seg,
      start: new Date(seg.start.getTime() + shiftS * 1000),
      end: new Date(seg.end.getTime() + shiftS * 1000),
      speaker,
      ...(tpl.label ? { label: tpl.label } : {}),
      perspective: 'receive' as const,
      arrivalOffsetS: shiftS,
    };
  });
}

/**
 * Compute the deterministic plan ID string.
 * Matches the ID generated by `ltx.html` and `api/ltx.php`.
 *
 * v2 plans use the FROZEN legacy 32-bit polynomial hash over JSON.stringify —
 * insertion-order-sensitive, kept byte-identical for compatibility
 * (LTX-SPECIFICATION.md §4.3). v3 plans use SHA-256 over RFC 8785 canonical
 * JSON (§4.5); the `-v3-` infix keeps the two id spaces disjoint.
 *
 * @example `"LTX-20260301-EARTHHQ-MARSHAR-v2-a3b2c1d0"`
 */
export function makePlanId(cfg: LtxPlan | LtxPlanV1 | AnyLtxPlan): string {
  const c       = upgradeConfig(cfg as LtxPlan | LtxPlanV1);
  const date    = new Date(c.start).toISOString().slice(0, 10).replace(/-/g, '');
  const nodes   = c.nodes || [];
  const hostStr = (nodes[0]?.name || 'HOST').replace(/\s+/g, '').toUpperCase().slice(0, 8);
  const nodeStr = nodes.length > 1
    ? nodes.slice(1).map(n => n.name.replace(/\s+/g, '').toUpperCase().slice(0, 4)).join('-').slice(0, 16)
    : 'RX';

  if ((c as { v: number }).v >= 3) {
    const digest = nodeCrypto.createHash('sha256')
      .update(Buffer.from(canonicalJSON(c), 'utf8'))
      .digest('hex');
    return `LTX-${date}-${hostStr}-${nodeStr}-v3-${digest.slice(0, 8)}`;
  }

  // FROZEN v2 path — simple 32-bit hash of the JSON, mirrors JS imul hash.
  const raw = JSON.stringify(c);
  let h = 0;
  for (let i = 0; i < raw.length; i++) {
    h = Math.imul(31, h) + raw.charCodeAt(i) | 0;
  }
  const hash = (h >>> 0).toString(16).padStart(8, '0');
  return `LTX-${date}-${hostStr}-${nodeStr}-v2-${hash}`;
}
