"""
test_fixtures.py — Cross-language fixture validation for interplanet_time.
Validates Python output against 54 reference entries from
interplanet-github/c/fixtures/reference.json (generated by the JS library).
"""

import json
import pathlib
import unittest

import sys
sys.path.insert(0, str(pathlib.Path(__file__).parents[1] / 'src'))

from interplanet_time import (
    Planet,
    get_planet_time,
    get_mtc,
    light_travel_seconds,
    helio_pos,
)

FIXTURES = pathlib.Path(__file__).parents[3] / "c" / "planet-time" / "fixtures" / "reference.json"


class TestCrossLanguage(unittest.TestCase):
    """54 reference entries from planet-time.js — validated against Python port."""

    @classmethod
    def setUpClass(cls):
        if not FIXTURES.exists():
            raise FileNotFoundError(
                f"reference.json not found at {FIXTURES}. "
                "Run the fixture generator from interplanet-github/c/ first."
            )
        data = json.loads(FIXTURES.read_text())
        cls.entries = data["entries"]

    def test_entry_count(self):
        self.assertEqual(len(self.entries), 54)

    def test_all_planet_time_fields(self):
        """Validate hour, minute, second, day_number, period_in_week,
        is_work_period, is_work_hour for all 54 entries."""
        mismatches = []
        for entry in self.entries:
            planet  = Planet[entry["planet"].upper()]
            utc_ms  = entry["utc_ms"]
            pt      = get_planet_time(planet, utc_ms)

            checks = [
                ("hour",           pt.hour,           entry["hour"]),
                ("minute",         pt.minute,         entry["minute"]),
                ("second",         pt.second,         entry["second"]),
                ("day_number",     pt.day_number,     entry["day_number"]),
                ("day_in_year",    pt.day_in_year,    entry["day_in_year"]),
                ("period_in_week", pt.period_in_week, entry["period_in_week"]),
                ("is_work_period", int(pt.is_work_period), entry["is_work_period"]),
                ("is_work_hour",   int(pt.is_work_hour),   entry["is_work_hour"]),
                ("time_str",       pt.time_str,        entry["time_str"]),
                ("time_str_full",  pt.time_str_full,   entry["time_str_full"]),
            ]

            for field, got, expected in checks:
                if got != expected:
                    mismatches.append(
                        f"[{entry['date_label']}/{entry['planet']}] "
                        f"{field}: got {got!r}, expected {expected!r}"
                    )

        if mismatches:
            self.fail(
                f"{len(mismatches)} mismatch(es):\n" + "\n".join(mismatches[:10])
            )

    def test_mars_sol_fields(self):
        """Validate sol_in_year and sols_per_year for Mars entries."""
        for entry in self.entries:
            if entry["planet"] != "mars":
                continue
            pt = get_planet_time(Planet.MARS, entry["utc_ms"])
            self.assertEqual(pt.sol_in_year,  entry["sol_in_year"],
                             f"sol_in_year mismatch at {entry['date_label']}")
            self.assertEqual(pt.sols_per_year, entry["sols_per_year"],
                             f"sols_per_year mismatch at {entry['date_label']}")

    def test_non_mars_sol_fields_none(self):
        """Non-Mars planets must have sol_in_year = None."""
        for entry in self.entries:
            if entry["planet"] in ("mars",):
                continue
            planet = Planet[entry["planet"].upper()]
            pt = get_planet_time(planet, entry["utc_ms"])
            self.assertIsNone(pt.sol_in_year,
                              f"sol_in_year should be None for {entry['planet']}")
            self.assertIsNone(pt.sols_per_year,
                              f"sols_per_year should be None for {entry['planet']}")

    def test_light_travel_seconds(self):
        """Validate light travel time (Earth→planet) to within ±1.0 s."""
        for entry in self.entries:
            if entry["light_travel_s"] is None:
                continue
            planet = Planet[entry["planet"].upper()]
            utc_ms = entry["utc_ms"]
            lt = light_travel_seconds(Planet.EARTH, planet, utc_ms)
            self.assertAlmostEqual(
                lt, entry["light_travel_s"], delta=1.0,
                msg=f"light_travel_s mismatch at {entry['date_label']}/{entry['planet']}"
            )

    def test_helio_r_au(self):
        """Validate heliocentric r in AU to within ±0.001 AU."""
        for entry in self.entries:
            planet = Planet[entry["planet"].upper()]
            utc_ms = entry["utc_ms"]
            hp = helio_pos(planet, utc_ms)
            self.assertAlmostEqual(
                hp.r, entry["helio_r_au"], delta=0.001,
                msg=f"helio_r_au mismatch at {entry['date_label']}/{entry['planet']}"
            )

    def test_mars_mtc(self):
        """Validate MTC sol, hour, minute, second for Mars entries that include it."""
        for entry in self.entries:
            if entry["planet"] != "mars" or entry.get("mtc") is None:
                continue
            mtc_ref = entry["mtc"]
            mtc     = get_mtc(entry["utc_ms"])
            self.assertEqual(mtc.sol,    mtc_ref["sol"],    f"MTC sol at {entry['date_label']}")
            self.assertEqual(mtc.hour,   mtc_ref["hour"],   f"MTC hour at {entry['date_label']}")
            self.assertEqual(mtc.minute, mtc_ref["minute"], f"MTC minute at {entry['date_label']}")
            self.assertEqual(mtc.second, mtc_ref["second"], f"MTC second at {entry['date_label']}")

    def test_year_number(self):
        """Validate year_number for all entries."""
        for entry in self.entries:
            planet = Planet[entry["planet"].upper()]
            pt = get_planet_time(planet, entry["utc_ms"])
            self.assertEqual(pt.year_number, entry["year_number"],
                             f"year_number mismatch at {entry['date_label']}/{entry['planet']}")


if __name__ == '__main__':
    unittest.main()
