/**
 * libitx.h — LTX (Light-Time eXchange) C library
 * Story 33.3 — C LTX library
 *
 * Pure C99, no external dependencies.
 * Independent of libinterplanet (the interplanetary time library).
 */

#ifndef LIBITX_H
#define LIBITX_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Version ─────────────────────────────────────────────────────────────── */

#define ITX_VERSION_STRING  "1.0.0"

/* ── Limits ──────────────────────────────────────────────────────────────── */

#define ITX_MAX_NODES     8      /**< Max nodes per plan */
#define ITX_MAX_SEGMENTS  32     /**< Max segment templates per plan */
#define ITX_MAX_STR       256    /**< Max string field length */
#define ITX_PLAN_ID_LEN   80     /**< Plan ID buffer size */
#define ITX_HASH_BUF      4096   /**< encodeHash output buffer size */
#define ITX_ICS_BUF       8192   /**< generateICS output buffer size */
#define ITX_URL_BUF       1024   /**< Per-node URL buffer size */
#define ITX_JSON_BUF      2048   /**< Internal JSON serialiser buffer */

/* ── Structs ─────────────────────────────────────────────────────────────── */

/** A participant node in an LTX session. */
typedef struct {
    char id[32];            /**< e.g. "N0", "N1" */
    char name[ITX_MAX_STR]; /**< e.g. "Earth HQ" */
    char role[32];          /**< "HOST" or "PARTICIPANT" */
    int  delay;             /**< One-way signal delay in seconds */
    char location[32];      /**< "earth", "mars", "moon" */
} itx_node_t;

/** A segment type+quantum entry in a plan's template list. */
typedef struct {
    char type[32];  /**< "PLAN_CONFIRM", "TX", "RX", "CAUCUS", "BUFFER", "MERGE" */
    int  q;         /**< Duration in quanta */
} itx_seg_tmpl_t;

/** A computed, timed segment with absolute UTC epoch milliseconds. */
typedef struct {
    char      type[32];
    int       q;
    long long start_ms; /**< UTC epoch milliseconds */
    long long end_ms;   /**< UTC epoch milliseconds */
    int       dur_min;  /**< Duration in minutes (q * quantum) */
} itx_segment_t;

/** An LTX session plan configuration (v2 schema). */
typedef struct {
    int             v;                              /**< Schema version (2) */
    char            title[ITX_MAX_STR];
    char            start[64];                      /**< ISO-8601 UTC start time */
    int             quantum;                        /**< Minutes per quantum */
    char            mode[32];                       /**< e.g. "LTX" */
    itx_node_t      nodes[ITX_MAX_NODES];
    int             node_count;
    itx_seg_tmpl_t  segments[ITX_MAX_SEGMENTS];
    int             seg_count;
} itx_plan_t;

/** A perspective URL for a specific node. */
typedef struct {
    char node_id[32];
    char name[ITX_MAX_STR];
    char role[32];
    char url[ITX_URL_BUF];
} itx_node_url_t;

/* ── Default constants (defined in libitx.c) ─────────────────────────────── */

extern const itx_seg_tmpl_t ITX_DEFAULT_SEGMENTS[7]; /**< Default 7-segment plan */
extern const int             ITX_DEFAULT_SEG_COUNT;   /**< 7 */
extern const int             ITX_DEFAULT_QUANTUM;     /**< 3 minutes per quantum */
extern const char            ITX_DEFAULT_API_BASE[];  /**< REST API base URL */

/* ── Plan creation ───────────────────────────────────────────────────────── */

/**
 * Initialise plan with default Earth HQ → Mars Hab-01 nodes and segments.
 *
 * @param plan       Output plan struct (caller allocates)
 * @param title      Session title (NULL → "LTX Session")
 * @param start_iso  ISO-8601 UTC start time string (NULL → "")
 * @param delay_sec  One-way light-travel delay for the remote node in seconds
 */
void itx_create_plan(itx_plan_t *plan, const char *title,
                     const char *start_iso, int delay_sec);

/* ── Segment computation ─────────────────────────────────────────────────── */

/**
 * Compute the timed segment array for a plan.
 *
 * @param plan      Input plan
 * @param segs      Output array (caller provides ITX_MAX_SEGMENTS slots)
 * @param seg_count Output: number of segments written
 */
void itx_compute_segments(const itx_plan_t *plan,
                          itx_segment_t *segs, int *seg_count);

/** Total session duration in minutes. */
int itx_total_min(const itx_plan_t *plan);

/* ── Plan ID ─────────────────────────────────────────────────────────────── */

/**
 * Compute the deterministic plan ID string.
 * Matches the ID generated by ltx-sdk.js and @interplanet/ltx.
 *
 * @param plan   Input plan
 * @param buf    Output buffer (at least ITX_PLAN_ID_LEN bytes)
 *
 * @example buf → "LTX-20260301-EARTHHQ-MARS-v2-a3b2c1d0"
 */
void itx_make_plan_id(const itx_plan_t *plan, char *buf);

/* ── Encoding ────────────────────────────────────────────────────────────── */

/**
 * Encode a plan to a URL-safe base64 hash fragment ("#l=…").
 * No padding characters (+, /, =).
 *
 * @param plan   Input plan
 * @param buf    Output buffer (at least ITX_HASH_BUF bytes)
 */
void itx_encode_hash(const itx_plan_t *plan, char *buf);

/**
 * Decode a plan from a URL hash fragment.
 * Accepts "#l=…", "l=…", or the raw base64 token.
 *
 * @param hash   Input hash string
 * @param plan   Output plan struct (caller allocates)
 * @return       0 on success, -1 on error
 */
int itx_decode_hash(const char *hash, itx_plan_t *plan);

/* ── Node URLs ────────────────────────────────────────────────────────────── */

/**
 * Build perspective URLs for all nodes in a plan.
 *
 * @param plan      Input plan
 * @param base_url  Base page URL (e.g. "https://interplanet.live/ltx.html")
 * @param urls      Output array (caller provides ITX_MAX_NODES slots)
 * @param url_count Output: number of URLs written
 */
void itx_build_node_urls(const itx_plan_t *plan, const char *base_url,
                         itx_node_url_t *urls, int *url_count);

/* ── ICS generation ──────────────────────────────────────────────────────── */

/**
 * Generate LTX-extended iCalendar (.ics) content for a plan.
 * Includes LTX-NODE, LTX-DELAY, LTX-LOCALTIME extension properties.
 *
 * @param plan   Input plan
 * @param buf    Output buffer (at least ITX_ICS_BUF bytes)
 */
void itx_generate_ics(const itx_plan_t *plan, char *buf);

/* ── Formatting ──────────────────────────────────────────────────────────── */

/**
 * Format a duration in seconds as "MM:SS" (< 1 hour) or "HH:MM:SS".
 *
 * @param seconds   Duration in seconds (negative clamped to 0)
 * @param buf       Output buffer (at least 12 bytes)
 */
void itx_format_hms(int seconds, char *buf);

/**
 * Format UTC epoch milliseconds as "HH:MM:SS UTC".
 *
 * @param epoch_ms  Epoch milliseconds
 * @param buf       Output buffer (at least 16 bytes)
 */
void itx_format_utc(long long epoch_ms, char *buf);

#ifdef __cplusplus
}
#endif

#endif /* LIBITX_H */
