"""ICS generation for LTX plans — Python port of ltx-sdk.js generateICS."""

from datetime import datetime, timezone
from typing import Optional

from ._models import LtxPlan
from ._core import (
    _as_plan_dict, compute_segments, compute_segments_for, make_plan_id,
)


def _fmt_dt(iso: str) -> str:
    """Convert ISO 8601 string to iCalendar DTSTART/DTEND format."""
    return iso.replace('-', '').replace(':', '').replace('Z', '').rstrip('0').rstrip('.') + 'Z'


def _to_id(name: str) -> str:
    return name.replace(' ', '-').upper()


def generate_ics(plan: LtxPlan, viewer_node_id: Optional[str] = None) -> str:
    """Generate LTX-extended iCalendar (.ics) content for a plan.

    Includes LTX-NODE, LTX-DELAY, LTX-LOCALTIME extension properties.
    Matches the output of ltx-sdk.js generateICS().

    With ``viewer_node_id``, emits the per-attendee form (Story 71.3,
    LTX-SPECIFICATION.md §14.5): one VEVENT per segment at that viewer's
    local arrival times.
    """
    if viewer_node_id:
        return _generate_viewer_ics(plan, viewer_node_id)
    segs     = compute_segments(plan)
    start    = plan.start
    end      = segs[-1].end
    plan_id  = make_plan_id(plan)
    nodes    = plan.nodes
    host     = nodes[0] if nodes else None
    parts    = nodes[1:] if len(nodes) > 1 else []
    seg_tpl  = ','.join(s.type for s in plan.segments)

    now_stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')

    host_name  = host.name if host else 'Earth HQ'
    part_names = ', '.join(p.name for p in parts) if parts else 'remote nodes'

    if parts:
        delay_desc = ' · '.join(
            f'{p.name}: {round(p.delay / 60)} min one-way' for p in parts
        )
    else:
        delay_desc = 'no participant delay configured'

    node_lines = [f'LTX-NODE:ID={_to_id(n.name)};ROLE={n.role}' for n in nodes]
    delay_lines = [
        f'LTX-DELAY;NODEID={_to_id(p.name)}:ONEWAY-MIN={round(p.delay)};'
        f'ONEWAY-MAX={round(p.delay) + 120};ONEWAY-ASSUMED={round(p.delay)}'
        for p in parts
    ]
    local_time_lines = [
        f'LTX-LOCALTIME:NODE={_to_id(n.name)};SCHEME=LMST;PARAMS=LONGITUDE:0E'
        for n in nodes if n.location == 'mars'
    ]

    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//InterPlanet//LTX v1.1//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'BEGIN:VEVENT',
        f'UID:{plan_id}@interplanet.live',
        f'DTSTAMP:{now_stamp}',
        f'DTSTART:{_fmt_dt(start)}',
        f'DTEND:{_fmt_dt(end)}',
        f'SUMMARY:{plan.title}',
        (f'DESCRIPTION:LTX session — {host_name} with {part_names}\\n'
         f'Signal delays: {delay_desc}\\n'
         f'Mode: {plan.mode} · Segment plan: {seg_tpl}\\n'
         'Generated by InterPlanet (https://interplanet.live)'),
        'LTX:1',
        f'LTX-PLANID:{plan_id}',
        f'LTX-QUANTUM:PT{plan.quantum}M',
        f'LTX-SEGMENT-TEMPLATE:{seg_tpl}',
        f'LTX-MODE:{plan.mode}',
        *node_lines,
        *delay_lines,
        'LTX-READINESS:CHECK=PT10M;REQUIRED=TRUE;FALLBACK=LTX-RELAY',
        *local_time_lines,
        'END:VEVENT',
        'END:VCALENDAR',
    ]
    return '\r\n'.join(lines)


def _pair_delay_lines(c: dict) -> list:
    """v3 pair-delay properties (LTX-SPECIFICATION.md §3.7.2), sorted by key."""
    delays = c.get('delays')
    if not delays:
        return []
    return [
        f'LTX-DELAY;PAIR={pair}:ONEWAY-ASSUMED={delays[pair]}'
        for pair in sorted(delays.keys())
    ]


def _generate_viewer_ics(plan, viewer_node_id: str) -> str:
    """Per-attendee export (§14.5): one VEVENT per segment at the viewer's
    local arrival times.  Attributed segments are shifted by
    pair_delay(speaker, viewer); summaries name the speaker and agenda label.
    """
    c        = _as_plan_dict(plan)
    segs     = compute_segments_for(c, viewer_node_id)
    plan_id  = make_plan_id(c)
    nodes    = c.get('nodes', [])
    viewer   = next((n for n in nodes if n.get('id') == viewer_node_id), None)
    now_stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')

    def name_of(node_id: str) -> str:
        node = next((n for n in nodes if n.get('id') == node_id), None)
        return (node or {}).get('name') or node_id

    viewer_name = (viewer or {}).get('name') or viewer_node_id
    title = c.get('title', '')

    events = []
    for i, seg in enumerate(segs):
        base = seg.get('label') or seg['type']
        if seg['perspective'] == 'transmit':
            summary = f'{base} — you present'
        elif seg['perspective'] == 'receive':
            summary = (f'{base} — {name_of(seg["speaker"])}, arriving after '
                       f'{round(seg["arrivalOffsetS"] / 60)} min light-time')
        else:
            summary = f'{base} ({title})'
        events.extend([
            'BEGIN:VEVENT',
            f'UID:{plan_id}-{viewer_node_id}-{i}@interplanet.live',
            f'DTSTAMP:{now_stamp}',
            f'DTSTART:{_fmt_dt(seg["start"])}',
            f'DTEND:{_fmt_dt(seg["end"])}',
            f'SUMMARY:{summary}',
            (f'DESCRIPTION:LTX {seg["type"]} segment of "{title}" '
             f'from the perspective of {viewer_name}'),
            'LTX:1',
            f'LTX-PLANID:{plan_id}',
            f'LTX-VIEWER:{viewer_node_id}',
            *([f'LTX-SPEAKER:{seg["speaker"]}'] if seg.get('speaker') else []),
            'END:VEVENT',
        ])

    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//InterPlanet//LTX v1.1//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        *events,
        *_pair_delay_lines(c),
        'END:VCALENDAR',
    ]
    return '\r\n'.join(lines)
