"""ICS generation for LTX plans — Python port of ltx-sdk.js generateICS."""

from datetime import datetime, timezone

from ._models import LtxPlan
from ._core import compute_segments, make_plan_id


def _fmt_dt(iso: str) -> str:
    """Convert ISO 8601 string to iCalendar DTSTART/DTEND format."""
    return iso.replace('-', '').replace(':', '').replace('Z', '').rstrip('0').rstrip('.') + 'Z'


def _to_id(name: str) -> str:
    return name.replace(' ', '-').upper()


def generate_ics(plan: LtxPlan) -> str:
    """Generate LTX-extended iCalendar (.ics) content for a plan.

    Includes LTX-NODE, LTX-DELAY, LTX-LOCALTIME extension properties.
    Matches the output of ltx-sdk.js generateICS().
    """
    segs     = compute_segments(plan)
    start    = plan.start
    end      = segs[-1].end
    plan_id  = make_plan_id(plan)
    nodes    = plan.nodes
    host     = nodes[0] if nodes else None
    parts    = nodes[1:] if len(nodes) > 1 else []
    seg_tpl  = ','.join(s.type for s in plan.segments)

    now_stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')

    host_name  = host.name if host else 'Earth HQ'
    part_names = ', '.join(p.name for p in parts) if parts else 'remote nodes'

    if parts:
        delay_desc = ' · '.join(
            f'{p.name}: {round(p.delay / 60)} min one-way' for p in parts
        )
    else:
        delay_desc = 'no participant delay configured'

    node_lines = [f'LTX-NODE:ID={_to_id(n.name)};ROLE={n.role}' for n in nodes]
    delay_lines = [
        f'LTX-DELAY;NODEID={_to_id(p.name)}:ONEWAY-MIN={round(p.delay)};'
        f'ONEWAY-MAX={round(p.delay) + 120};ONEWAY-ASSUMED={round(p.delay)}'
        for p in parts
    ]
    local_time_lines = [
        f'LTX-LOCALTIME:NODE={_to_id(n.name)};SCHEME=LMST;PARAMS=LONGITUDE:0E'
        for n in nodes if n.location == 'mars'
    ]

    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//InterPlanet//LTX v1.1//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'BEGIN:VEVENT',
        f'UID:{plan_id}@interplanet.live',
        f'DTSTAMP:{now_stamp}',
        f'DTSTART:{_fmt_dt(start)}',
        f'DTEND:{_fmt_dt(end)}',
        f'SUMMARY:{plan.title}',
        (f'DESCRIPTION:LTX session — {host_name} with {part_names}\\n'
         f'Signal delays: {delay_desc}\\n'
         f'Mode: {plan.mode} · Segment plan: {seg_tpl}\\n'
         'Generated by InterPlanet (https://interplanet.live)'),
        'LTX:1',
        f'LTX-PLANID:{plan_id}',
        f'LTX-QUANTUM:PT{plan.quantum}M',
        f'LTX-SEGMENT-TEMPLATE:{seg_tpl}',
        f'LTX-MODE:{plan.mode}',
        *node_lines,
        *delay_lines,
        'LTX-READINESS:CHECK=PT10M;REQUIRED=TRUE;FALLBACK=LTX-RELAY',
        *local_time_lines,
        'END:VEVENT',
        'END:VCALENDAR',
    ]
    return '\r\n'.join(lines)
